# Generated by Django 4.1 on 2022-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('favorite_language', models.CharField(max_length=20)),
                ('experience', models.CharField(choices=[('Junior', 'Jr'), ('Pleno', 'Pl'), ('Senior', 'Sn')], default='Junior', max_length=20)),
            ],
        ),
    ]
